version: '3.8'

services:
  telegram-summary-bot:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Persist SQLite database
      - bot_data:/app/data
    environment:
      # Load from .env file
      - SECRET_TELEGRAM_API_TOKEN=${SECRET_TELEGRAM_API_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ACCOUNT_ID=${ACCOUNT_ID:-local-deployment}
      - DATABASE_PATH=/app/data/messages.sqlite
      - PORT=3000
      - WEBHOOK_URL=${WEBHOOK_URL}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 16 */6 * *}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  bot_data:
    driver: local